const ALL_ARTWORKS_URL = process.env.ALL_ARTWORKS_URL;
const IMAGES_URL = process.env.IMAGES_URL;
const ARTWORK_SEARCH_URL = process.env.ARTWORK_SEARCH_URL;

export { ALL_ARTWORKS_URL, ARTWORK_SEARCH_URL, IMAGES_URL };
